# Generated by Django 4.2.7 on 2023-11-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibraryAuthor',
        ),
    ]
