# Generated by Django 4.2.7 on 2023-11-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_delete_libraryauthor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_mane',
            new_name='first_name',
        ),
    ]
